before_script:
    - apt-get update -qq
    - apt-get install -y build-essential autoconf automake libtool lsb-release
    - lsb_release -a
    - uname -a

test:
  script:
    - lsb_release -a
    - uname -a
    - ./autogen.sh
    - ./configure
    - make
    - make check
    - install -m 755 /bin/true /usr/local/bin/git2cl
    - make distcheck
